---
version: 2.1
references:
  workspace_root: &workspace_root
    /tmp/workspace
  attach_workspace: &attach_workspace
    attach_workspace:
      at: *workspace_root

orbs:
  python: circleci/python@1.2

jobs:
  build:
    docker:
      -
        image: "cimg/python:3.8"
    steps:
      - checkout
      -
        python/install-packages:
          app-dir: ~/project/src/main
          pkg-manager: pip
  build-static:
    docker:
      -
        image: "cimg/python:3.8"
    steps:
      - checkout
      -
        run:
          command: |
              sudo apt-get update
              sudo apt-get install hugo
              echo "listing current dir"
              pwd
              ls -al
              cd ~/project/ui/hacktober.instacodes.net && hugo -d /tmp/workspace/public_html
          name: "Install hugo"
      -
        persist_to_workspace:
          paths:
            - public_html
          root: *workspace_root
  deploy-serverless:
    docker:
      -
        image: "cimg/python:3.8"
    steps:
      - checkout
      -
        run:
          command: "curl -o- -L https://slss.io/install | bash -x"
          name: "Install Serverless"
      -
        run:
          command: |
            export PATH="$HOME/.serverless/bin:$PATH" && sls deploy
          name: "Deploy Serverless Function"
  deploy-static:
    docker:
      -
        image: "cimg/python:3.8"
    steps:
      - *attach_workspace
      -
        add_ssh_keys:
          fingerprints:
            - "70:44:86:3c:bb:f6:eb:f1:82:8a:85:8d:a5:3b:8d:08"
      - run:
          command: |
            apt-get update
            apt-get install rsync
          name: "Installing rsync"
      - run:
          command: "rsync -avz /tmp/workspace/public_html $SSH_USER@$SSH_HOST:/tmp/"
          name: "Deploy Over SSH"

workflows:
  build-and-deploy:
    jobs:
      - build
      -
        deploy-serverless:
          filters:
            branches:
              only: main
          requires:
            - build
      - build-static
      -
        deploy-static:
          filters:
            branches:
              only: ui
          requires:
            - build-static
