---
version: 2.1
references:
  workspace_root: &workspace_root
    /tmp/workspace
  attach_workspace: &attach_workspace
    attach_workspace:
      at: *workspace_root

orbs:
  python: circleci/python@1.2

jobs:
  build:
    docker:
      -
        image: "cimg/python:3.8"
    steps:
      - checkout
      -
        python/install-packages:
          app-dir: ~/project/src/main
          pkg-manager: pip
  build-ui-contents:
    docker:
      -
        image: "cimg/python:3.8"
    steps:
      - checkout
      - run: git submodule sync
      - run: git submodule update --init --recursive
      -
        python/install-packages:
          app-dir: ~/project/src/main
          pkg-manager: pip
      -
        run:
          command: |
              sudo apt-get update
              sudo apt-get install hugo
              echo "listing current dir"
              python src/main/site_builder.py
              cd ~/project/ui/hacktober.instacodes.net && hugo -d /tmp/workspace/public_html
          name: "Install hugo"
      -
        persist_to_workspace:
          paths:
            - public_html
          root: *workspace_root
  build-ui:
    docker:
      -
        image: "cimg/python:3.8"
    steps:
      - checkout
      - run: git submodule sync
      - run: git submodule update --init --recursive
      -
        python/install-packages:
          app-dir: ~/project/src/main
          pkg-manager: pip
      -
        run:
          command: |
              sudo apt-get update
              sudo apt-get install hugo
              cd ~/project/ui/hacktober.instacodes.net && hugo -d /tmp/workspace/public_html
          name: "Install hugo"
      -
        persist_to_workspace:
          paths:
            - public_html
          root: *workspace_root
  deploy-serverless:
    docker:
      -
        image: "cimg/python:3.8"
    steps:
      - checkout
      -
        run:
          command: "curl -o- -L https://slss.io/install | bash -x"
          name: "Install Serverless"
      -
        run:
          command: |
            export PATH="$HOME/.serverless/bin:$PATH" && sls deploy
          name: "Deploy Serverless Function"
  deploy-static:
    docker:
      -
        image: "cimg/python:3.8"
    steps:
      - *attach_workspace
      -
        add_ssh_keys:
          fingerprints:
            - "70:44:86:3c:bb:f6:eb:f1:82:8a:85:8d:a5:3b:8d:08"
      - run:
          command: |
            sudo apt-get update
            sudo apt-get install rsync
            mkdir -p ~/.ssh
            ssh-keyscan $SSH_HOST >> ~/.ssh/known_hosts
          name: "Installing rsync"
      - run:
          name: "Creating archive"
          command: "pushd /tmp/workspace/public_html && zip -r ../public . && popd"
      - run:
          command: "rsync -avz /tmp/workspace/public.zip $SSH_USER@$SSH_HOST:/tmp/"
          name: "Copy Over SSH"
      - run:
          name: "Deploy Over SSH"
          command: |
            ssh $SSH_USER@$SSH_HOST "unzip -o /tmp/public.zip -d /var/www/html/hacktoberfest/ && sudo systemctl restart httpd.service"

workflows:
  build-and-deploy:
    jobs:
      - build
      -
        deploy-serverless:
          filters:
            branches:
              only: main
          requires:
            - build
      - build-ui-contents:
          filters:
            branches:
              only: ui-content-refresh
      - build-ui:
          filters:
            branches:
              only: ui
      -
        deploy-static:
          filters:
            branches:
              only: ui-content-refresh
          requires:
            - build-ui-contents
      -
        deploy-static:
          filters:
            branches:
              only: ui
          requires:
            - build-ui
